### PR TITLE
Added debug flag to ServiceManager and host param to Service

### PR DESCRIPTION
**Pull request by AlecAivazis**
@janjaapbos, this is my take on adding support for the `debug` flag. As you can see, I did something really similar to your previous solution except that I moved the re-initialization to the `run` method, which means the manager doesn't have to be aware of anything outside of the argument. 

I realize this isn't ideal since the service is initialized twice, but I think it's better to keep the manager as unaware of the service as possible which directly translates into a leaner api for the service objects.

Let me know what you think and if this works for you. 

Also, I simplified the config logic by always creating a configuration for the service, regardless if you passed in a value or not. My rationale was that we can use this config to store internal options regardless if the user provided any customization.

### CODE REVIEW

**Comment by janjaapbos** [comment]
Perhaps we could prevent this issue by initialising the service by the manager, instead of handing an initialised service to the manager. E.g. in the recipeBook example, the server.py module would just define a Service class (based on nautilus.ModelService) and its Config class (based on nautilus.config.Config).

With those two classes the service manager (or any other program that wants to use the service) can just import these two classes, initialise the Config (and adjust it with startup options) and subsequently initialise the service with the customised config.

**Comment by AlecAivazis** [comment]
By "initializing" do you mean calling `init_service` or by instantiating the service in the body of `ServiceManager.run`? I think the latter is probably very close to the "right" approach since it keeps all of the initialization concerns in the service and prevents the need for calling the init functions again. 

For example,
```python
import nautilus
from nautilus.models import BaseModel
from nautilus.models.fields import CharField

class ServiceConfig:
    database_url = 'sqlite://foo.db'

class MyModel(BaseModel):
    my_attribute = CharField()

myService = nautilus.ModelService

manager = nautilus.ServiceManager(
    service=myService,
    service_args=dict(
        model=MyModel,
        config=ServiceConfig,
    )
)

```

I feel a bit weird about passing the constructor arguments as a separate dict but I could get over it.

**Comment by AlecAivazis** [comment]
One solution could be something like

```python
# assuming the imports/definitions above...

class RecipeService(nautilus.ModelService):
    model = MyModel

manager = nautilus.ServiceManager(RecipeService, config=ServiceConfig)
```

There are a few different possible variations on the class definition. For example,

```python
class RecipeService(nautilus.ModelService):
    class Meta:
        model = MyModel
```
or even
```python
class RecipeService(nautilus.ModelService, model=MyModel): pass
```

That last one requires very specific metaclass magic for each type of service which isn't ideal

**Comment by AlecAivazis** [comment]
One benefit of the class based approach is to support mixins at a service level which could open the door to some cool behaviors/plugins.

**Comment by janjaapbos** [comment]
Yes, something like this would be my preference. The first example is easy to understand and to extend.

`# assuming the imports/definitions above...

class RecipeService(nautilus.ModelService):
    model = MyModel

class RecipeConfig(nautilus.config.Config):
     conf_var1 = xxx

manager = nautilus.ServiceManager(RecipeService, config=RecipeConfig)
`

This would also allow you to have a custom ServiceConfig that is a base config for all your services, in the case that you have many services that have 90% the same settings for your deployment. And as you mention, it is easier to mixin / extend services.

**Comment by AlecAivazis** [comment]
I'm closing this since I just opened a PR with the new implementation

**Pull request closed without merging**
